config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "products#index"

  resources :orders, only: :create

  delete 'delete_order', to: 'orders#delete_order'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_products, dependent: :destroy
  has_many :products, through: :orders_products

  class << self

    # create order and order's product
    def create_order(product_id, user_id)
  		order = find_or_create_by(user_id: user_id)
    	order.orders_products.create(product_id: product_id)
    end

    # check if order has any products
    def is_placed_order?(user_id, product_id)
    	get_order_products(user_id, product_id).any? ? true : false
    end

    # cancel the order
    def delete_order(user_id, product_id)
    	get_order_products(user_id, product_id).destroy_all
    end

    # after 24 hours cancel the ordered products automatically
    def auto_cancel_order
      orders = self.where('created_at > ?', 24.hours.ago)
    	if orders.any?
        orders.map{ |o| o.orders_products.delete_all }
      end
    end

    private

    # Get the order and their products
    def get_order_products(user_id, product_id)
      order = find_by(user_id: user_id)
      order.orders_products.where(product_id: product_id)
    end
  end

end

app/models/orders_product.rb
class OrdersProduct < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders_products
  has_many :orders, through: :orders_products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def create
		if current_user
			@order = Order.create_order(params[:product_id], current_user.id)
				respond_to do |format|
					format.js
				end
		else
			redirect_to new_user_session_path
		end
	end

	def delete_order
		@order = Order.delete_order(current_user.id, params[:product_id])
		respond_to do |format|
			format.js
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all.order("id desc")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def add_currency(price)
		'$' + price.to_s
	end

	def is_order_placed?(product_id)
		Order.is_placed_order?(current_user.id, product_id)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_place_the_order.html.erb
<%= button_to "Place the order", orders_path(product_id: product_id), method: 'POST', class: "place-order", remote: true %>

app/views/orders/_placed_order.html.erb
<%= button_to "Order placed", orders_path(product_id: product_id), method: 'POST', class: "place-order", remote: true %>

<%= button_to "Cancel", delete_order_path(product_id: product_id), method: :delete, class: "place-order", remote: true %>
	

app/views/orders/create.js.erb
query = document.querySelector("#order_<%= params[:product_id] %>");
query.outerHTML = 
	"<%= j render 'orders/placed_order', product_id:  params[:product_id] %>"

app/views/orders/delete_order.js.erb
query = document.querySelector("#order_<%= params[:product_id] %>");
query.outerHTML = 
	"<%= j render 'orders/place_the_order', product_id:  params[:product_id] %>"

app/views/products/_product.html.erb
<div class="product">
  <%= image_tag "mobile.jpeg" %>
  <h1><%= product.name %></h1>
  <p class="price"><%= add_currency(product.price) %></p>
  <p><%= product.color %></p>
  <div id= "order_<%= product.id %>">
		<% if current_user && is_order_placed?(product.id) %>
			<%= render 'orders/placed_order', product_id: product.id %>
		<% else %>
			<%= render 'orders/place_the_order', product_id: product.id %>
		<% end %>
	</div>
</div> 

app/views/products/index.html.erb
<div class="card">
	<%= render @products %>
</div>